"""add push subscriptions and timer notified flag

Revision ID: 3a9bd01e38a6
Revises: 507217c92e3e
Create Date: 2026-09-27 18:45:13.915675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9bd01e38a6'
down_revision: Union[str, None] = '507217c92e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # server_default added by hand: without it, ADD COLUMN NOT NULL fails against an existing,
    # already-populated timers table (same fix as the archived/is_admin/skill migrations before
    # this one). Default true (not false!) is deliberate: existing timers predate the scheduler
    # that sends the "expired" push, so treating them as "already notified" avoids a burst of
    # pushes for old, long-expired timers the instant this migration runs.
    op.add_column('timers', sa.Column('notified', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timers', 'notified')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
