"""add conversation skill field

Revision ID: 507217c92e3e
Revises: 7ac904825de8
Create Date: 2026-09-27 18:31:37.091909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507217c92e3e'
down_revision: Union[str, None] = '7ac904825de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: without it, ADD COLUMN NOT NULL fails against an existing,
    # already-populated conversations table (Postgres/SQLite both reject it) - same fix as the
    # archived/is_admin migrations before this one.
    op.add_column(
        'conversations',
        sa.Column('skill', sa.String(length=32), nullable=False, server_default='general'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'skill')
    # ### end Alembic commands ###
