"""add conversation archived flag

Revision ID: 594c16ac8f73
Revises: a11d8062af01
Create Date: 2026-09-27 17:49:28.289507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594c16ac8f73'
down_revision: Union[str, None] = 'a11d8062af01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: this DB already has real conversations (see the previous
    # migration's note on the same hazard for is_admin) - existing ones default to unarchived.
    op.add_column('conversations', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived')
    # ### end Alembic commands ###
