"""add admin fields and app settings

Revision ID: a11d8062af01
Revises: e4de3fa9c0bf
Create Date: 2026-09-27 17:19:12.113148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11d8062af01'
down_revision: Union[str, None] = 'e4de3fa9c0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('registration_open', sa.Boolean(), nullable=False),
    sa.Column('system_paused', sa.Boolean(), nullable=False),
    sa.Column('system_paused_message', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default is required here: this DB already has real users (this isn't a fresh
    # install), and Postgres/SQLite both reject a NOT NULL column added to a non-empty table
    # without one. Existing users default to is_admin=False.
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # Data migration: the "first registered user becomes admin" bootstrap (see app/api/auth.py)
    # only fires on a brand-new install, where registration itself sets it. An existing,
    # already-populated database has users but none of them went through that bootstrap - so
    # promote whoever registered first, otherwise nobody could ever reach the admin endpoints.
    users = sa.table(
        'users',
        sa.column('id', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('is_admin', sa.Boolean),
    )
    conn = op.get_bind()
    earliest_user_id = conn.execute(
        sa.select(users.c.id).order_by(users.c.created_at.asc()).limit(1)
    ).scalar()
    if earliest_user_id is not None:
        conn.execute(users.update().where(users.c.id == earliest_user_id).values(is_admin=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
